---
title: "Presentation"
format:
  revealjs:
    theme: dark
    navigation-mode: vertical
    transition: convex
    embed-resources: true
---


```{r}
#| label: setup
#| include: false

pacman::p_load(tidyverse)
theme_set(theme_minimal())

# Read more about revelajs in quarto here: https://quarto.org/docs/presentations/revealjs/

```

```{r}
dt = read_csv("company_financials_csv.zip",
              show_col_types = FALSE)
```

# Apple's profits

## Apple's profits as a time series

```{r}
dt |> 
  filter(tic == "AAPL") |> 
  ggplot(aes(x = datadate, y = oiadpq)) +
  geom_line() +
  scale_y_continuous(limits = c(-1000, 42000)) +
  labs(x = NULL, y = "Operating Income After Depreciation")
```


## Apple's profits - quarterly trend

```{r}
dt |> 
  filter(tic == "AAPL" & fyearq >= 2005) |> 
  ggplot(aes(x = datadate, y = oiadpq)) +
  geom_col(aes(fill = as.factor(fqtr))) +
  labs(x = NULL, y = "Operating Income After Depreciation", fill = "Fiscal\nQuarter")
```


# Apple's sales

## Apple's sales as a time series

```{r}
dt |> 
  filter(tic == "AAPL") |> 
  ggplot(aes(x = datadate, y = saleq)) +
  geom_line() +
  labs(x = NULL, y = "Sales")
```

## Apple's sales - quarterly trend

```{r}
dt |> 
  filter(tic == "AAPL" & fyearq >= 2005) |> 
  ggplot(aes(x = datadate, y = saleq)) +
  geom_col(aes(fill = as.factor(fqtr))) +
  labs(x = NULL, y = "Sales", fill = "Fiscal\nQuarter")
```